[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='<Your-Address>'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
